/*
 This file is auto-generated by the statrep package.
 Do not edit this file or your changes will be lost.
 Edit the LaTeX file instead.
 
 See the statrep package documentation and the file
 statrep.cfg for information on these settings.
 */
 
 
%include "H:/GraphicsGroup/StatRep/explore/pcp/pcp_SR_preamble.sas" /nosource;
/* Remove all output files. */
%cleandir(H:/GraphicsGroup/StatRep/explore/pcp, tex, tex);
%cleandir(H:/GraphicsGroup/StatRep/explore/pcp, png, png);
%cleandir(H:/GraphicsGroup/StatRep/explore/pcp, lst, lst);


/* Start program with a null title. */
title;

options sasautos=("H:/GitHub/srosanba/sas-parallel-coordinates-plot/src" sasautos);
ods graphics / height=3in;

%output(basics)
%parallel
   (data=sashelp.iris
   ,var=sepallength sepalwidth petallength petalwidth
   ,group=species
   );

%endoutput(basics)

%write(basics,store=basics,objects=SGPlot,type=graphic) 

ods graphics / height=3in;

%output(datavalues)
%parallel
   (data=sashelp.iris
   ,var=sepallength sepalwidth petallength petalwidth
   ,group=species
   ,axistype=datavalues
   );

%endoutput(datavalues)

%write(datavalues,store=datavalues,objects=SGPlot,type=graphic) 

